# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 21:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('phrasebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convcon',
            name='audiofilulinkki',
            field=models.CharField(default=datetime.datetime(2015, 12, 4, 21, 41, 54, 698905, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
