# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrasebook', '0002_convcon_audiofilulinkki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convcon',
            name='audiofilulinkki',
            field=models.CharField(max_length=200),
        ),
    ]
