# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 09:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('phrasebook', '0003_auto_20151207_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='convcon',
            name='tagi',
            field=models.CharField(default=datetime.datetime(2015, 12, 12, 9, 25, 1, 189871, tzinfo=utc), max_length=15),
            preserve_default=False,
        ),
    ]
